language: php

php:
  - 7.2.11
  - 7.3.0

before_install:
  - composer install

script:
  - mkdir reports
  - ./vendor/bin/phpcs src
  - ./vendor/bin/phpmd src html phpmd.xml > reports/phpmd.html
  - ./vendor/bin/phpunit --coverage-clover ./reports/clover.xml
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
